version: "2.2"

services:
  mail:
    build:
      context: ../
      dockerfile: deployment/Dockerfile
    container_name: mail
    environment:
      RAVEN_CONFIG_DSN: "YOUR_DSN_HERE"
      RAVEN_CONFIG_RELEASE: "dev"
      ENABLE_RAVEN: "False"
    networks:
      - test-network

  mail_postgres:
    image: postgres:9.5
    container_name: postgres.mail
    environment:
      LC_ALL: C.UTF-8
      POSTGRES_DB: mail
      POSTGRES_USER: mail
      POSTGRES_PASSWORD: mail
    networks:
      - test-network

networks:
  test-network:
    driver: bridge