version: "2"

services:
  mail:
    build:
      context: ../
      dockerfile: deployment/Dockerfile
    env_file: ../.env
    container_name: mail
    environment:
      DJANGO_CONFIGURATION: Development
    networks:
      - test-network

  mail_postgres:
    image: postgres:9.5
    container_name: postgres.mail
    environment:
      LC_ALL: C.UTF-8
      POSTGRES_DB: mail
      POSTGRES_USER: mail
      POSTGRES_PASSWORD: mail
    networks:
      - test-network

networks:
  test-network:
    driver: bridge