# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-21 11:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_mailbox', '__latest__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default=None, max_length=254, null=True, unique=True)),
                ('name', models.CharField(max_length=128, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CustomMailbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.IntegerField(default=None, null=True, verbose_name='Owner')),
                ('smtp_host', models.CharField(max_length=128)),
                ('smtp_port', models.IntegerField(default=587)),
            ],
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.IntegerField(default=None, null=True, verbose_name='Owner')),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bcc', models.TextField(null=True)),
                ('draft', models.BooleanField(default=False)),
                ('chain', models.UUIDField(default=uuid.uuid4)),
                ('subject', models.CharField(blank=True, max_length=255, null=True, verbose_name='Subject')),
                ('message_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Message ID')),
                ('from_header', models.CharField(blank=True, max_length=255, null=True, verbose_name='From header')),
                ('to_header', models.TextField(blank=True, null=True, verbose_name='To header')),
                ('outgoing', models.BooleanField(default=False, verbose_name='Outgoing')),
                ('body', models.TextField(blank=True, null=True, verbose_name='Body')),
                ('encoded', models.BooleanField(default=False, help_text='True if the e-mail body is Base64 encoded', verbose_name='Encoded')),
                ('processed', models.DateTimeField(auto_now_add=True, verbose_name='Processed')),
                ('read', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Read')),
                ('eml', models.FileField(help_text='Original full content of message', null=True, upload_to='messages', verbose_name='Raw message contents')),
                ('folder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.Folder')),
                ('in_reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mail_replies', to='api.Mail', verbose_name='In reply to')),
            ],
            options={
                'verbose_name': 'E-mail message',
                'verbose_name_plural': 'E-mail messages',
                'ordering': ['-processed'],
            },
        ),
        migrations.CreateModel(
            name='Inbox',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('django_mailbox.mailbox',),
        ),
        migrations.AddField(
            model_name='mail',
            name='mailbox',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_mailbox.Mailbox', verbose_name='Mailbox'),
        ),
        migrations.AddField(
            model_name='folder',
            name='mailbox',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='django_mailbox.Mailbox'),
        ),
        migrations.AddField(
            model_name='custommailbox',
            name='inbox',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mailer', to='api.Inbox'),
        ),
        migrations.AddField(
            model_name='contact',
            name='folder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Folder'),
        ),
    ]
