# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-04 14:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_mailbox', '__latest__'),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomMailbox',
        ),
        migrations.CreateModel(
            name='CustomMailbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smtp_host', models.CharField(max_length=128)),
                ('smtp_port', models.IntegerField(default=587)),
                ('inbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailer', to='django_mailbox.Mailbox')),
            ],
        ),
    ]
