# Generated by Django 2.0.7 on 2018-07-21 12:51

from django.db import migrations, models
import django.db.models.deletion
import django_mailbox.utils


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headers', models.TextField(blank=True, null=True, verbose_name='Headers')),
                ('document', models.FileField(upload_to=django_mailbox.utils.get_attachment_save_path, verbose_name='Document')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='api.Mail', verbose_name='Message')),
            ],
            options={
                'verbose_name': 'Message attachment',
                'verbose_name_plural': 'Message attachments',
            },
        ),
        migrations.AlterField(
            model_name='contact',
            name='folder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Folder'),
        ),
    ]
