# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-05 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180604_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='bcc',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='mail',
            name='draft',
            field=models.BooleanField(default=False),
        ),
    ]
