# Generated by Django 2.0.7 on 2018-07-23 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180721_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
