# Generated by Django 2.0.7 on 2018-07-25 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_mail_is_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='folder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='api.Folder'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='in_reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mail_replies', to='api.Mail', verbose_name='In reply to'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='mailbox',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_mailbox.Mailbox', verbose_name='Mailbox'),
        ),
    ]
