# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-05 09:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180605_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custommailbox',
            name='inbox',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mailer', to='django_mailbox.Mailbox'),
        ),
    ]
