# Generated by Django 2.0.7 on 2018-07-26 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180725_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='mailbox',
        ),
    ]
