# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-13 15:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_mailbox', '0007_auto_20180529_1124'),
        ('api', '0004_auto_20180605_0921'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inbox',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('django_mailbox.mailbox',),
        ),
        migrations.AlterField(
            model_name='custommailbox',
            name='inbox',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mailer', to='api.Inbox'),
        ),
    ]
