# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-14 19:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180613_1559'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mail',
            options={'ordering': ['-processed']},
        ),
    ]
