# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-14 19:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20180614_1901'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='folder',
            options={'ordering': ['name']},
        ),
    ]
