# Generated by Django 2.0.7 on 2018-07-30 08:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


def create_chains(apps, schema_editor):
    db_alias = schema_editor.connection.alias

    Chain = apps.get_model("api", "Chain")
    Mail = apps.get_model("api", "Mail")

    chains = Mail.objects.using(db_alias).values_list("chain", flat=True).order_by("chain").distinct("chain")
    for chain in chains:
        Chain.objects.using(db_alias).create(id=chain)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_mail_folder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RunPython(create_chains, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='mail',
            name='chain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Chain'),
        ),
        migrations.AddField(
            model_name='folder',
            name='chains',
            field=models.ManyToManyField(to='api.Chain'),
        ),
    ]
