# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-22 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20180614_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='custommailbox',
            name='owner',
            field=models.IntegerField(default=None, null=True, verbose_name='Owner'),
        ),
        migrations.AddField(
            model_name='folder',
            name='owner',
            field=models.IntegerField(default=None, null=True, verbose_name='Owner'),
        ),
    ]
