# Generated by Django 2.0.7 on 2018-08-10 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20180806_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='custommailbox',
            name='smtp_secure',
            field=models.CharField(choices=[('tls', 'TLS'), ('ssl', 'SSL')], default='ssl', max_length=4),
        ),
        migrations.AlterField(
            model_name='custommailbox',
            name='smtp_port',
            field=models.IntegerField(default=465),
        ),
    ]
