# Generated by Django 2.0.7 on 2018-08-15 12:39
from datetime import datetime

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20180810_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='from_header',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='From header'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='to_header',
            field=models.TextField(blank=True, default='', verbose_name='To header'),
        ),
    ]
