# Generated by Django 2.0.7 on 2018-08-15 12:39
import email
import base64
from email.utils import parsedate_to_datetime
from django.db import migrations


def update_dates(apps, schema_editor):
    Mail = apps.get_model("api", "Mail")

    mails = Mail.objects.filter(date=None)
    for mail in mails.iterator():
        if mail.encoded:
            body = base64.b64decode(mail.body.encode('ascii'))
        else:
            body = mail.body.encode('utf-8')
        msg = email.message_from_bytes(body)
        if 'date' in msg:
            mail.date = parsedate_to_datetime(msg['date'])
            mail.save()
            print(">> id:{} date:{}".format(mail.pk, mail.date))


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20180815_1239'),
    ]

    operations = [
        migrations.RunPython(update_dates, migrations.RunPython.noop, atomic=False),
    ]