# Generated by Django 2.0.7 on 2018-10-25 19:53

from django.db import migrations, models
import django.db.models.deletion
import mail.api.utils

def convert_mailboxes(apps, schema_editor):
    NewMailbox = apps.get_model('api', 'Mailbox')
    OldMailbox = apps.get_model('api', 'CustomMailbox')
    for old_mailbox in OldMailbox.objects.all():
        new_mailbox = NewMailbox.objects.create(
            id=old_mailbox.inbox.id,
            name=old_mailbox.inbox.name,
            owner=old_mailbox.owner,
            smtp_port=old_mailbox.smtp_port,
            smtp_host=old_mailbox.smtp_host,
            smtp_secure=old_mailbox.smtp_secure,
            shared=old_mailbox.shared,
            uri=old_mailbox.inbox.uri,
            from_email=old_mailbox.inbox.from_email,
            active=old_mailbox.inbox.active,
            last_polling=old_mailbox.inbox.last_polling
        )
        print("Migrationg {}".format(old_mailbox))

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mailbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('owner', models.IntegerField(default=None, null=True, verbose_name='Owner')),
                ('smtp_host', models.CharField(max_length=128)),
                ('smtp_port', models.IntegerField(default=465)),
                ('smtp_secure', models.CharField(choices=[('tls', 'TLS'), ('ssl', 'SSL')], default='ssl', max_length=4)),
                ('custom_query', models.CharField(max_length=512, null=True)),
                ('shared', models.BooleanField(default=False)),
                ('uri', models.CharField(blank=True, default=None, help_text="Example: imap+ssl://myusername:mypassword@someserver <br /><br />Internet transports include 'imap' and 'pop3'; common local file transports include 'maildir', 'mbox', and less commonly 'babyl', 'mh', and 'mmdf'. <br /><br />Be sure to urlencode your username and password should they contain illegal characters (like @, :, etc).", max_length=255, null=True, verbose_name='URI')),
                ('from_email', models.CharField(blank=True, default=None, help_text="Example: MailBot &lt;mailbot@yourdomain.com&gt;<br />'From' header to set for outgoing email.<br /><br />If you do not use this e-mail inbox for outgoing mail, this setting is unnecessary.<br />If you send e-mail without setting this, your 'From' header will'be set to match the setting `DEFAULT_FROM_EMAIL`.", max_length=255, null=True, verbose_name='From email')),
                ('active', models.BooleanField(default=True, help_text='Check this e-mail inbox for new e-mail messages during polling cycles.  This checkbox does not have an effect upon whether mail is collected here when this mailbox receives mail from a pipe, and does not affect whether e-mail messages can be dispatched from this mailbox. ', verbose_name='Active')),
                ('last_polling', models.DateTimeField(blank=True, help_text='The time of last successful polling for messages.It is blank for new mailboxes and is not set for mailboxes that only receive messages via a pipe.', null=True, verbose_name='Last polling')),
            ],
            options={
                'verbose_name': 'Mailbox',
                'verbose_name_plural': 'Mailboxes',
            },
        ),
        migrations.RunPython(convert_mailboxes, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='custommailbox',
            name='inbox',
        ),
        migrations.DeleteModel(
            name='Inbox',
        ),
        migrations.AlterField(
            model_name='attachment',
            name='document',
            field=models.FileField(upload_to=mail.api.utils.get_attachment_save_path, verbose_name='Document'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='mailbox',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Mailbox', verbose_name='Mailbox'),
        ),
        migrations.DeleteModel(
            name='CustomMailbox',
        ),
    ]
