# Generated by Django 2.0.7 on 2019-11-21 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20181122_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailbox',
            name='smtp_secure',
            field=models.CharField(choices=[('tls', 'TLS'), ('ssl', 'SSL')], default='ssl', max_length=4, null=True),
        ),
    ]
