# Generated by Django 2.2.6 on 2022-11-07 20:56

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20191121_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailbox',
            name='smtp_host',
        ),
        migrations.RemoveField(
            model_name='mailbox',
            name='smtp_port',
        ),
        migrations.RemoveField(
            model_name='mailbox',
            name='smtp_secure',
        ),
        migrations.AddField(
            model_name='mailbox',
            name='out_config',
            field=jsonfield.fields.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='mailbox',
            name='out_type',
            field=models.CharField(choices=[('smtp', 'SMTP'), ('unisender', 'Unisender')], max_length=128, null=True, verbose_name='Outgoing transport'),
        ),
        migrations.AlterField(
            model_name='mailbox',
            name='active',
            field=models.BooleanField(blank=True, default=True, help_text='Check this e-mail inbox for new e-mail messages during polling cycles.  This checkbox does not have an effect upon whether mail is collected here when this mailbox receives mail from a pipe, and does not affect whether e-mail messages can be dispatched from this mailbox. ', verbose_name='Active'),
        ),
    ]
